USE [BAE_4_6_TARGET]
GO

/****** Object:  Table [dbo].[BW_CUBOID_ROWID_COLUMN_ID_MAP]    Script Date: 15-03-2022 22:26:50 ******/
DROP TABLE [dbo].[BW_CUBOID_ROWID_COLUMN_ID_MAP]
GO

/****** Object:  Table [dbo].[BW_MIGRATION_OBJECT_MAP]    Script Date: 15-03-2022 22:26:50 ******/
DROP TABLE [dbo].[BW_MIGRATION_OBJECT_MAP]
GO

/****** Object:  Table [dbo].[BW_DEPLOYED_PACKAGES]    Script Date: 15-03-2022 22:26:50 ******/
DROP TABLE [dbo].[BW_DEPLOYED_PACKAGES]
GO

/****** Object:  Table [dbo].[BW_DEPLOYED_PACKAGES]    Script Date: 15-03-2022 22:26:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BW_DEPLOYED_PACKAGES](
	[ID] [int] IDENTITY(1000,1) NOT NULL,
	[PACKAGE_NAME] [varchar](512) NOT NULL,
	[SOURCE_SERVER] [varchar](512) NOT NULL,
	[PACKAGE_CREATION_DATE] [datetime] NOT NULL,
	[PACKAGE_DEPLOYED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_BW_DEPLOYED_PACKAGES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[BW_MIGRATION_OBJECT_MAP]    Script Date: 15-03-2022 22:26:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BW_MIGRATION_OBJECT_MAP](
	[ID] [int] IDENTITY(1000,1) NOT NULL,
	[OBJECT_NAME] [varchar](512) NOT NULL,
	[SOURCE_SERVER] [varchar](512) NOT NULL,
	[TARGET_SERVER] [varchar](512) NOT NULL,
	[SOURCE_OBJECT_ID] [int] NOT NULL,
	[TARGET_OBJECT_ID] [int] NOT NULL,
	[OBJECT_TYPE] [varchar](512) NOT NULL,
	[CREATION_TX_ID] [int] NOT NULL,
	[PACKAGE_NAME] [varchar](512) NOT NULL,
 CONSTRAINT [PK_BW_MIGRATION_OBJECT_MAP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

/****** Object:  Table [dbo].[BW_CUBOID_ROWID_COLUMN_ID_MAP]    Script Date: 15-03-2022 22:26:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BW_CUBOID_ROWID_COLUMN_ID_MAP](
	[ID] [int] IDENTITY(1000,1) NOT NULL,
	[OBJECT_NAME] [varchar](512) NOT NULL,
	[CUBOID_NAME] [varchar](512) NOT NULL,
	[SOURCE_SERVER] [varchar](512) NOT NULL,
	[TARGET_SERVER] [varchar](512) NOT NULL,
	[SOURCE_CUBOID_ID] [int] NOT NULL,
	[TARGET_CUBOID_ID] [int] NOT NULL,
	[SOURCE_OBJECT_ID] [int] NOT NULL,
	[TARGET_OBJECT_ID] [int] NOT NULL,
	[OBJECT_TYPE] [varchar](512) NOT NULL,
	[SEQUENCE_NUMBER] [int] NOT NULL,
 CONSTRAINT [PK_BW_CUBOID_ROWID_COLUMN_ID_MAP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


