USE [BAE_4_6_TARGET]
GO

/****** Object:  StoredProcedure [dbo].[BW_ADD_MIGRATION_OBJECT_MAP]    Script Date: 15-03-2022 22:28:05 ******/
DROP PROCEDURE [dbo].[BW_ADD_MIGRATION_OBJECT_MAP]
GO

/****** Object:  StoredProcedure [dbo].[BW_ADD_DEPLOYED_PACKAGES]    Script Date: 15-03-2022 22:28:05 ******/
DROP PROCEDURE [dbo].[BW_ADD_DEPLOYED_PACKAGES]
GO

/****** Object:  StoredProcedure [dbo].[BW_GET_MIGRATED_OBJECT_ID_FROM_MIGRATION_OBJECT_MAP]    Script Date: 15-03-2022 22:28:05 ******/
DROP PROCEDURE [dbo].[BW_GET_MIGRATED_OBJECT_ID_FROM_MIGRATION_OBJECT_MAP]
GO

/****** Object:  StoredProcedure [dbo].[BW_ADD_CUBOID_ROWID_COLUMN_ID_MAP_FOR_MIGRATION]    Script Date: 15-03-2022 22:28:05 ******/
DROP PROCEDURE [dbo].[BW_ADD_CUBOID_ROWID_COLUMN_ID_MAP_FOR_MIGRATION]
GO

/****** Object:  StoredProcedure [dbo].[BW_ADD_CUBOID_ROWID_COLUMN_ID_MAP_FOR_MIGRATION]    Script Date: 15-03-2022 22:28:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[BW_ADD_CUBOID_ROWID_COLUMN_ID_MAP_FOR_MIGRATION] 
	@OBJECT_NAME VARCHAR(512) , 
	@CUBOID_NAME VARCHAR(512) , 
	@SOURCE_SERVER VARCHAR(512) , 
	@TARGET_SERVER  VARCHAR(512) , 
	@SOURCE_CUBOID_ID INT , 
	@TARGET_CUBOID_ID INT , 
	@SOURCE_OBJECT_ID INT , 
	@TARGET_OBJECT_ID INT , 
	@OBJECT_TYPE VARCHAR(512) , 
	@SEQUENCE_NUMBER INT ,
	@PACKAGE_NAME VARCHAR(512) 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	IF NOT EXISTS (SELECT * FROM BW_CUBOID_ROWID_COLUMN_ID_MAP WHERE
				OBJECT_NAME = @OBJECT_NAME AND 
				CUBOID_NAME = @CUBOID_NAME AND 
				SOURCE_SERVER = @SOURCE_SERVER AND 
				TARGET_SERVER = @TARGET_SERVER AND
				SOURCE_CUBOID_ID = @SOURCE_CUBOID_ID AND
				TARGET_CUBOID_ID = @TARGET_CUBOID_ID AND
				SOURCE_OBJECT_ID = @SOURCE_OBJECT_ID AND 
				TARGET_OBJECT_ID = @TARGET_OBJECT_ID AND
				OBJECT_TYPE = @OBJECT_TYPE) 
	BEGIN								
		INSERT BW_CUBOID_ROWID_COLUMN_ID_MAP
			([OBJECT_NAME], CUBOID_NAME, SOURCE_SERVER, TARGET_SERVER, SOURCE_CUBOID_ID, TARGET_CUBOID_ID, SOURCE_OBJECT_ID, TARGET_OBJECT_ID, OBJECT_TYPE, SEQUENCE_NUMBER)
			VALUES
				(@OBJECT_NAME, @CUBOID_NAME, @SOURCE_SERVER, @TARGET_SERVER, @SOURCE_CUBOID_ID, @TARGET_CUBOID_ID, @SOURCE_OBJECT_ID, @TARGET_OBJECT_ID,				@OBJECT_TYPE, @SEQUENCE_NUMBER)
	END
END



GO

/****** Object:  StoredProcedure [dbo].[BW_GET_MIGRATED_OBJECT_ID_FROM_MIGRATION_OBJECT_MAP]    Script Date: 15-03-2022 22:28:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[BW_GET_MIGRATED_OBJECT_ID_FROM_MIGRATION_OBJECT_MAP] 
	@OBJECT_NAME VARCHAR(512), 
	@SOURCE_SERVER VARCHAR(512), 
	@SOURCE_OBJECT_ID INT, 
	@OBJECT_TYPE VARCHAR(512),
	@TARGET_OBJECT_ID INTEGER OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	SET @TARGET_OBJECT_ID = -1

	SELECT @TARGET_OBJECT_ID = TARGET_OBJECT_ID FROM BW_MIGRATION_OBJECT_MAP 
		WHERE SOURCE_SERVER = @SOURCE_SERVER AND 
				SOURCE_OBJECT_ID = @SOURCE_OBJECT_ID AND
					OBJECT_TYPE = @OBJECT_TYPE

END



GO

/****** Object:  StoredProcedure [dbo].[BW_ADD_DEPLOYED_PACKAGES]    Script Date: 15-03-2022 22:28:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[BW_ADD_DEPLOYED_PACKAGES] 
	@PACKAGE_NAME VARCHAR(512), 
	@SOURCE_SERVER VARCHAR(512), 
	@PACKAGE_CREATION_DATE DATETIME,
	@PACKAGE_ID INTEGER OUTPUT
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	INSERT INTO BW_DEPLOYED_PACKAGES
		(PACKAGE_NAME, SOURCE_SERVER, PACKAGE_CREATION_DATE, PACKAGE_DEPLOYED_DATE)
		VALUES 
		(@PACKAGE_NAME, @SOURCE_SERVER, @PACKAGE_CREATION_DATE, GETUTCDATE())

	SET @PACKAGE_ID = @@IDENTITY

END



GO

/****** Object:  StoredProcedure [dbo].[BW_ADD_MIGRATION_OBJECT_MAP]    Script Date: 15-03-2022 22:28:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[BW_ADD_MIGRATION_OBJECT_MAP] 
	@OBJECT_NAME VARCHAR(512), 
	@SOURCE_SERVER VARCHAR(512), 
	@TARGET_SERVER VARCHAR(512), 
	@SOURCE_OBJECT_ID INT, 
	@TARGET_OBJECT_ID INT, 
	@CREATION_TX_ID INT, 
	@OBJECT_TYPE VARCHAR(512), 
	@PACKAGE_NAME	 VARCHAR(512)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	IF NOT EXISTS(SELECT * FROM BW_MIGRATION_OBJECT_MAP 
					WHERE OBJECT_NAME = @OBJECT_NAME
						AND SOURCE_SERVER = @SOURCE_SERVER
							AND TARGET_SERVER = @TARGET_SERVER
								AND SOURCE_OBJECT_ID = @SOURCE_OBJECT_ID
									AND TARGET_OBJECT_ID = @TARGET_OBJECT_ID
										AND OBJECT_TYPE = @OBJECT_TYPE)
	BEGIN
		INSERT INTO BW_MIGRATION_OBJECT_MAP 
			(OBJECT_NAME, SOURCE_SERVER, TARGET_SERVER, SOURCE_OBJECT_ID, TARGET_OBJECT_ID,  OBJECT_TYPE, CREATION_TX_ID, PACKAGE_NAME)
				VALUES 
					(@OBJECT_NAME, @SOURCE_SERVER, @TARGET_SERVER, @SOURCE_OBJECT_ID, @TARGET_OBJECT_ID, @OBJECT_TYPE, @CREATION_TX_ID, @PACKAGE_NAME)
			
	END

END



GO


