/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;


import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
/**
 * Cell
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-09-18T12:35:03.779Z")
public class Cell   {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("rowId")
  private Integer rowId = null;

  @JsonProperty("colId")
  private Integer colId = null;

  @JsonProperty("rowSequence")
  private Float rowSequence = null;

  @JsonProperty("colSequence")
  private Float colSequence = null;

  @JsonProperty("cellValue")
  private String cellValue = null;

  @JsonProperty("cellFormula")
  private String cellFormula = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("tid")
  private Integer tid = null;

  @JsonProperty("changeFlag")
  private Integer changeFlag = null;

  @JsonProperty("access")
  private Integer access = null;

  public Cell id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Cell rowId(Integer rowId) {
    this.rowId = rowId;
    return this;
  }

  /**
   * Get rowId
   * @return rowId
   **/
  @JsonProperty("rowId")
  @ApiModelProperty(value = "")
  public Integer getRowId() {
    return rowId;
  }

  public void setRowId(Integer rowId) {
    this.rowId = rowId;
  }

  public Cell colId(Integer colId) {
    this.colId = colId;
    return this;
  }

  /**
   * Get colId
   * @return colId
   **/
  @JsonProperty("colId")
  @ApiModelProperty(value = "")
  public Integer getColId() {
    return colId;
  }

  public void setColId(Integer colId) {
    this.colId = colId;
  }

  public Cell rowSequence(Float rowSequence) {
    this.rowSequence = rowSequence;
    return this;
  }

  /**
   * Get rowSequence
   * @return rowSequence
   **/
  @JsonProperty("rowSequence")
  @ApiModelProperty(value = "")
  public Float getRowSequence() {
    return rowSequence;
  }

  public void setRowSequence(Float rowSequence) {
    this.rowSequence = rowSequence;
  }

  public Cell colSequence(Float colSequence) {
    this.colSequence = colSequence;
    return this;
  }

  /**
   * Get colSequence
   * @return colSequence
   **/
  @JsonProperty("colSequence")
  @ApiModelProperty(value = "")
  public Float getColSequence() {
    return colSequence;
  }

  public void setColSequence(Float colSequence) {
    this.colSequence = colSequence;
  }

  public Cell cellValue(String cellValue) {
    this.cellValue = cellValue;
    return this;
  }

  /**
   * Get cellValue
   * @return cellValue
   **/
  @JsonProperty("cellValue")
  @ApiModelProperty(value = "")
  public String getCellValue() {
    return cellValue;
  }

  public void setCellValue(String cellValue) {
    this.cellValue = cellValue;
  }

  public Cell cellFormula(String cellFormula) {
    this.cellFormula = cellFormula;
    return this;
  }

  /**
   * Get cellFormula
   * @return cellFormula
   **/
  @JsonProperty("cellFormula")
  @ApiModelProperty(value = "")
  public String getCellFormula() {
    return cellFormula;
  }

  public void setCellFormula(String cellFormula) {
    this.cellFormula = cellFormula;
  }

  public Cell active(Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   **/
  @JsonProperty("active")
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Cell tid(Integer tid) {
    this.tid = tid;
    return this;
  }

  /**
   * Get tid
   * @return tid
   **/
  @JsonProperty("tid")
  @ApiModelProperty(value = "")
  public Integer getTid() {
    return tid;
  }

  public void setTid(Integer tid) {
    this.tid = tid;
  }

  public Cell changeFlag(Integer changeFlag) {
    this.changeFlag = changeFlag;
    return this;
  }

  /**
   * Get changeFlag
   * @return changeFlag
   **/
  @JsonProperty("changeFlag")
  @ApiModelProperty(value = "")
  public Integer getChangeFlag() {
    return changeFlag;
  }

  public void setChangeFlag(Integer changeFlag) {
    this.changeFlag = changeFlag;
  }

  public Cell access(Integer access) {
    this.access = access;
    return this;
  }

  /**
   * Get access
   * @return access
   **/
  @JsonProperty("access")
  @ApiModelProperty(value = "")
  public Integer getAccess() {
    return access;
  }

  public void setAccess(Integer access) {
    this.access = access;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cell cell = (Cell) o;
    return Objects.equals(this.id, cell.id) &&
        Objects.equals(this.rowId, cell.rowId) &&
        Objects.equals(this.colId, cell.colId) &&
        Objects.equals(this.rowSequence, cell.rowSequence) &&
        Objects.equals(this.colSequence, cell.colSequence) &&
        Objects.equals(this.cellValue, cell.cellValue) &&
        Objects.equals(this.cellFormula, cell.cellFormula) &&
        Objects.equals(this.active, cell.active) &&
        Objects.equals(this.tid, cell.tid) &&
        Objects.equals(this.changeFlag, cell.changeFlag) &&
        Objects.equals(this.access, cell.access);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rowId, colId, rowSequence, colSequence, cellValue, cellFormula, active, tid, changeFlag, access);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cell {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rowId: ").append(toIndentedString(rowId)).append("\n");
    sb.append("    colId: ").append(toIndentedString(colId)).append("\n");
    sb.append("    rowSequence: ").append(toIndentedString(rowSequence)).append("\n");
    sb.append("    colSequence: ").append(toIndentedString(colSequence)).append("\n");
    sb.append("    cellValue: ").append(toIndentedString(cellValue)).append("\n");
    sb.append("    cellFormula: ").append(toIndentedString(cellFormula)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    tid: ").append(toIndentedString(tid)).append("\n");
    sb.append("    changeFlag: ").append(toIndentedString(changeFlag)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

