/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

//@JsonInclude(JsonInclude.Include.NON_EMPTY)
/**
 * ChangedCell
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-12-11T08:59:59.552Z")
public class ChangedCell   {
  @JsonProperty("cellId")
  private Integer cellId = null;

  @JsonProperty("rowId")
  private Integer rowId = null;

  @JsonProperty("columnId")
  private Integer columnId = null;

  @JsonProperty("rowSequenceNumber")
  private Float rowSequenceNumber = null;

  @JsonProperty("columnSequenceNumber")
  private Float columnSequenceNumber = null;

  @JsonProperty("cellValue")
  private String cellValue = null;

  @JsonProperty("cellFormula")
  private String cellFormula = null;

  @JsonProperty("isActive")
  private Boolean isActive = null;

  @JsonProperty("txId")
  private Integer txId = null;

  @JsonProperty("changeFlag")
  private Integer changeFlag = null;

  @JsonProperty("access")
  private Integer access = null;

  public ChangedCell cellId(Integer cellId) {
    this.cellId = cellId;
    return this;
  }

  /**
   * Get cellId
   * @return cellId
   **/
  @JsonProperty("cellId")
  @ApiModelProperty(value = "")
  public Integer getCellId() {
    return cellId;
  }

  public void setCellId(Integer cellId) {
    this.cellId = cellId;
  }

  public ChangedCell rowId(Integer rowId) {
    this.rowId = rowId;
    return this;
  }

  /**
   * Get rowId
   * @return rowId
   **/
  @JsonProperty("rowId")
  @ApiModelProperty(value = "")
  public Integer getRowId() {
    return rowId;
  }

  public void setRowId(Integer rowId) {
    this.rowId = rowId;
  }

  public ChangedCell columnId(Integer columnId) {
    this.columnId = columnId;
    return this;
  }

  /**
   * Get columnId
   * @return columnId
   **/
  @JsonProperty("columnId")
  @ApiModelProperty(value = "")
  public Integer getColumnId() {
    return columnId;
  }

  public void setColumnId(Integer columnId) {
    this.columnId = columnId;
  }

  public ChangedCell rowSequenceNumber(Float rowSequenceNumber) {
    this.rowSequenceNumber = rowSequenceNumber;
    return this;
  }

  /**
   * Get rowSequenceNumber
   * @return rowSequenceNumber
   **/
  @JsonProperty("rowSequenceNumber")
  @ApiModelProperty(value = "")
  public Float getRowSequenceNumber() {
    return rowSequenceNumber;
  }

  public void setRowSequenceNumber(Float rowSequenceNumber) {
    this.rowSequenceNumber = rowSequenceNumber;
  }

  public ChangedCell columnSequenceNumber(Float columnSequenceNumber) {
    this.columnSequenceNumber = columnSequenceNumber;
    return this;
  }

  /**
   * Get columnSequenceNumber
   * @return columnSequenceNumber
   **/
  @JsonProperty("columnSequenceNumber")
  @ApiModelProperty(value = "")
  public Float getColumnSequenceNumber() {
    return columnSequenceNumber;
  }

  public void setColumnSequenceNumber(Float columnSequenceNumber) {
    this.columnSequenceNumber = columnSequenceNumber;
  }

  public ChangedCell cellValue(String cellValue) {
    this.cellValue = cellValue;
    return this;
  }

  /**
   * Get cellValue
   * @return cellValue
   **/
  @JsonProperty("cellValue")
  @ApiModelProperty(value = "")
  public String getCellValue() {
    return cellValue;
  }

  public void setCellValue(String cellValue) {
    this.cellValue = cellValue;
  }

  public ChangedCell cellFormula(String cellFormula) {
    this.cellFormula = cellFormula;
    return this;
  }

  /**
   * Get cellFormula
   * @return cellFormula
   **/
  @JsonProperty("cellFormula")
  @ApiModelProperty(value = "")
  public String getCellFormula() {
    return cellFormula;
  }

  public void setCellFormula(String cellFormula) {
    this.cellFormula = cellFormula;
  }

  public ChangedCell isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   **/
  @JsonProperty("isActive")
  @ApiModelProperty(value = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public ChangedCell txId(Integer txId) {
    this.txId = txId;
    return this;
  }

  /**
   * Get txId
   * @return txId
   **/
  @JsonProperty("txId")
  @ApiModelProperty(value = "")
  public Integer getTxId() {
    return txId;
  }

  public void setTxId(Integer txId) {
    this.txId = txId;
  }

  public ChangedCell changeFlag(Integer changeFlag) {
    this.changeFlag = changeFlag;
    return this;
  }

  /**
   * Get changeFlag
   * @return changeFlag
   **/
  @JsonProperty("changeFlag")
  @ApiModelProperty(value = "")
  public Integer getChangeFlag() {
    return changeFlag;
  }

  public void setChangeFlag(Integer changeFlag) {
    this.changeFlag = changeFlag;
  }

  public ChangedCell access(Integer access) {
    this.access = access;
    return this;
  }

  /**
   * Get access
   * @return access
   **/
  @JsonProperty("access")
  @ApiModelProperty(value = "")
  public Integer getAccess() {
    return access;
  }

  public void setAccess(Integer access) {
    this.access = access;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangedCell changedCell = (ChangedCell) o;
    return Objects.equals(this.cellId, changedCell.cellId) &&
        Objects.equals(this.rowId, changedCell.rowId) &&
        Objects.equals(this.columnId, changedCell.columnId) &&
        Objects.equals(this.rowSequenceNumber, changedCell.rowSequenceNumber) &&
        Objects.equals(this.columnSequenceNumber, changedCell.columnSequenceNumber) &&
        Objects.equals(this.cellValue, changedCell.cellValue) &&
        Objects.equals(this.cellFormula, changedCell.cellFormula) &&
        Objects.equals(this.isActive, changedCell.isActive) &&
        Objects.equals(this.txId, changedCell.txId) &&
        Objects.equals(this.changeFlag, changedCell.changeFlag) &&
        Objects.equals(this.access, changedCell.access);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cellId, rowId, columnId, rowSequenceNumber, columnSequenceNumber, cellValue, cellFormula, isActive, txId, changeFlag, access);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangedCell {\n");
    
    sb.append("    cellId: ").append(toIndentedString(cellId)).append("\n");
    sb.append("    rowId: ").append(toIndentedString(rowId)).append("\n");
    sb.append("    columnId: ").append(toIndentedString(columnId)).append("\n");
    sb.append("    rowSequenceNumber: ").append(toIndentedString(rowSequenceNumber)).append("\n");
    sb.append("    columnSequenceNumber: ").append(toIndentedString(columnSequenceNumber)).append("\n");
    sb.append("    cellValue: ").append(toIndentedString(cellValue)).append("\n");
    sb.append("    cellFormula: ").append(toIndentedString(cellFormula)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    changeFlag: ").append(toIndentedString(changeFlag)).append("\n");
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

