/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.Whiteboard;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
/**
 * Collaboration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class Collaboration   {
  @JsonProperty("collabId")
  private Integer collabId = null;

  @JsonProperty("collabName")
  private String collabName = null;

  @JsonProperty("collabPurpose")
  private String collabPurpose = null;

  @JsonProperty("wbList")
  private List<Whiteboard> wbList = null;

  public Collaboration collabId(Integer collabId) {
    this.collabId = collabId;
    return this;
  }

  /**
   * Get collabId
   * @return collabId
   **/
  @JsonProperty("collabId")
  @ApiModelProperty(value = "")
  public Integer getCollabId() {
    return collabId;
  }

  public void setCollabId(Integer collabId) {
    this.collabId = collabId;
  }

  public Collaboration collabName(String collabName) {
    this.collabName = collabName;
    return this;
  }

  /**
   * Get collabName
   * @return collabName
   **/
  @JsonProperty("collabName")
  @ApiModelProperty(value = "")
  public String getCollabName() {
    return collabName;
  }

  public void setCollabName(String collabName) {
    this.collabName = collabName;
  }

  public Collaboration collabPurpose(String collabPurpose) {
    this.collabPurpose = collabPurpose;
    return this;
  }

  /**
   * Get collabPurpose
   * @return collabPurpose
   **/
  @JsonProperty("collabPurpose")
  @ApiModelProperty(value = "")
  public String getCollabPurpose() {
    return collabPurpose;
  }

  public void setCollabPurpose(String collabPurpose) {
    this.collabPurpose = collabPurpose;
  }

  public Collaboration wbList(List<Whiteboard> wbList) {
    this.wbList = wbList;
    return this;
  }

  public Collaboration addWbListItem(Whiteboard wbListItem) {
    if (this.wbList == null) {
      this.wbList = new ArrayList<Whiteboard>();
    }
    this.wbList.add(wbListItem);
    return this;
  }

  /**
   * Get wbList
   * @return wbList
   **/
  @JsonProperty("wbList")
  @ApiModelProperty(value = "")
  public List<Whiteboard> getWbList() {
    return wbList;
  }

  public void setWbList(List<Whiteboard> wbList) {
    this.wbList = wbList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Collaboration collaboration = (Collaboration) o;
    return Objects.equals(this.collabId, collaboration.collabId) &&
        Objects.equals(this.collabName, collaboration.collabName) &&
        Objects.equals(this.collabPurpose, collaboration.collabPurpose) &&
        Objects.equals(this.wbList, collaboration.wbList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collabId, collabName, collabPurpose, wbList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Collaboration {\n");
    
    sb.append("    collabId: ").append(toIndentedString(collabId)).append("\n");
    sb.append("    collabName: ").append(toIndentedString(collabName)).append("\n");
    sb.append("    collabPurpose: ").append(toIndentedString(collabPurpose)).append("\n");
    sb.append("    wbList: ").append(toIndentedString(wbList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

