/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
/**
 * Column
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-05-10T09:36:40.808Z")
public class Column   {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("seqNo")
  private Float seqNo = null;

  @JsonProperty("previousColumnid")
  private Integer previousColumnid = null;

  @JsonProperty("previousColumnOffset")
  private Integer previousColumnOffset = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("tid")
  private Integer tid = null;

  public Column id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Column name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Column seqNo(Float seqNo) {
    this.seqNo = seqNo;
    return this;
  }

  /**
   * Get seqNo
   * @return seqNo
   **/
  @JsonProperty("seqNo")
  @ApiModelProperty(value = "")
  public Float getSeqNo() {
    return seqNo;
  }

  public void setSeqNo(Float seqNo) {
    this.seqNo = seqNo;
  }

  public Column previousColumnid(Integer previousColumnid) {
    this.previousColumnid = previousColumnid;
    return this;
  }

  /**
   * Get previousColumnid
   * @return previousColumnid
   **/
  @JsonProperty("previousColumnid")
  @ApiModelProperty(value = "")
  public Integer getPreviousColumnid() {
    return previousColumnid;
  }

  public void setPreviousColumnid(Integer previousColumnid) {
    this.previousColumnid = previousColumnid;
  }

  public Column previousColumnOffset(Integer previousColumnOffset) {
    this.previousColumnOffset = previousColumnOffset;
    return this;
  }

  /**
   * Get previousColumnOffset
   * @return previousColumnOffset
   **/
  @JsonProperty("previousColumnOffset")
  @ApiModelProperty(value = "")
  public Integer getPreviousColumnOffset() {
    return previousColumnOffset;
  }

  public void setPreviousColumnOffset(Integer previousColumnOffset) {
    this.previousColumnOffset = previousColumnOffset;
  }

  public Column active(Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   **/
  @JsonProperty("active")
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Column tid(Integer tid) {
    this.tid = tid;
    return this;
  }

  /**
   * Get tid
   * @return tid
   **/
  @JsonProperty("tid")
  @ApiModelProperty(value = "")
  public Integer getTid() {
    return tid;
  }

  public void setTid(Integer tid) {
    this.tid = tid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Column column = (Column) o;
    return Objects.equals(this.id, column.id) &&
        Objects.equals(this.name, column.name) &&
        Objects.equals(this.seqNo, column.seqNo) &&
        Objects.equals(this.previousColumnid, column.previousColumnid) &&
        Objects.equals(this.previousColumnOffset, column.previousColumnOffset) &&
        Objects.equals(this.active, column.active) &&
        Objects.equals(this.tid, column.tid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, seqNo, previousColumnid, previousColumnOffset, active, tid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Column {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    seqNo: ").append(toIndentedString(seqNo)).append("\n");
    sb.append("    previousColumnid: ").append(toIndentedString(previousColumnid)).append("\n");
    sb.append("    previousColumnOffset: ").append(toIndentedString(previousColumnOffset)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    tid: ").append(toIndentedString(tid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

