/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
/**
 * GridTransaction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class GridTransaction   {
  @JsonProperty("txId")
  private Integer txId = null;

  @JsonProperty("txCreatedByEmail")
  private String txCreatedByEmail = null;

  @JsonProperty("txCreationTimeUTC")
  private Date txCreationTimeUTC = null;

  @JsonProperty("comment")
  private String comment = null;

  @JsonProperty("rowAdded")
  private Boolean rowAdded = null;

  @JsonProperty("rowDeleted")
  private Boolean rowDeleted = null;

  @JsonProperty("columnAdded")
  private Boolean columnAdded = null;

  @JsonProperty("cellUpdated")
  private Boolean cellUpdated = null;

  @JsonProperty("formulaUpdated")
  private Boolean formulaUpdated = null;

  @JsonProperty("baselineAdded")
  private Boolean baselineAdded = null;

  public GridTransaction txId(Integer txId) {
    this.txId = txId;
    return this;
  }

  /**
   * Get txId
   * @return txId
   **/
  @JsonProperty("txId")
  @ApiModelProperty(value = "")
  public Integer getTxId() {
    return txId;
  }

  public void setTxId(Integer txId) {
    this.txId = txId;
  }

  public GridTransaction txCreatedByEmail(String txCreatedByEmail) {
    this.txCreatedByEmail = txCreatedByEmail;
    return this;
  }

  /**
   * Get txCreatedByEmail
   * @return txCreatedByEmail
   **/
  @JsonProperty("txCreatedByEmail")
  @ApiModelProperty(value = "")
  public String getTxCreatedByEmail() {
    return txCreatedByEmail;
  }

  public void setTxCreatedByEmail(String txCreatedByEmail) {
    this.txCreatedByEmail = txCreatedByEmail;
  }

  public GridTransaction txCreationTimeUTC(Date txCreationTimeUTC) {
    this.txCreationTimeUTC = txCreationTimeUTC;
    return this;
  }

  /**
   * Get txCreationTimeUTC
   * @return txCreationTimeUTC
   **/
  @JsonProperty("txCreationTimeUTC")
  @ApiModelProperty(value = "")
  public Date getTxCreationTimeUTC() {
    return txCreationTimeUTC;
  }

  public void setTxCreationTimeUTC(Date txCreationTimeUTC) {
    this.txCreationTimeUTC = txCreationTimeUTC;
  }

  public GridTransaction comment(String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Get comment
   * @return comment
   **/
  @JsonProperty("comment")
  @ApiModelProperty(value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public GridTransaction rowAdded(Boolean rowAdded) {
    this.rowAdded = rowAdded;
    return this;
  }

  /**
   * Get rowAdded
   * @return rowAdded
   **/
  @JsonProperty("rowAdded")
  @ApiModelProperty(value = "")
  public Boolean isRowAdded() {
    return rowAdded;
  }

  public void setRowAdded(Boolean rowAdded) {
    this.rowAdded = rowAdded;
  }

  public GridTransaction rowDeleted(Boolean rowDeleted) {
    this.rowDeleted = rowDeleted;
    return this;
  }

  /**
   * Get rowDeleted
   * @return rowDeleted
   **/
  @JsonProperty("rowDeleted")
  @ApiModelProperty(value = "")
  public Boolean isRowDeleted() {
    return rowDeleted;
  }

  public void setRowDeleted(Boolean rowDeleted) {
    this.rowDeleted = rowDeleted;
  }

  public GridTransaction columnAdded(Boolean columnAdded) {
    this.columnAdded = columnAdded;
    return this;
  }

  /**
   * Get columnAdded
   * @return columnAdded
   **/
  @JsonProperty("columnAdded")
  @ApiModelProperty(value = "")
  public Boolean isColumnAdded() {
    return columnAdded;
  }

  public void setColumnAdded(Boolean columnAdded) {
    this.columnAdded = columnAdded;
  }

  public GridTransaction cellUpdated(Boolean cellUpdated) {
    this.cellUpdated = cellUpdated;
    return this;
  }

  /**
   * Get cellUpdated
   * @return cellUpdated
   **/
  @JsonProperty("cellUpdated")
  @ApiModelProperty(value = "")
  public Boolean isCellUpdated() {
    return cellUpdated;
  }

  public void setCellUpdated(Boolean cellUpdated) {
    this.cellUpdated = cellUpdated;
  }

  public GridTransaction formulaUpdated(Boolean formulaUpdated) {
    this.formulaUpdated = formulaUpdated;
    return this;
  }

  /**
   * Get formulaUpdated
   * @return formulaUpdated
   **/
  @JsonProperty("formulaUpdated")
  @ApiModelProperty(value = "")
  public Boolean isFormulaUpdated() {
    return formulaUpdated;
  }

  public void setFormulaUpdated(Boolean formulaUpdated) {
    this.formulaUpdated = formulaUpdated;
  }

  public GridTransaction baselineAdded(Boolean baselineAdded) {
    this.baselineAdded = baselineAdded;
    return this;
  }

  /**
   * Get baselineAdded
   * @return baselineAdded
   **/
  @JsonProperty("baselineAdded")
  @ApiModelProperty(value = "")
  public Boolean isBaselineAdded() {
    return baselineAdded;
  }

  public void setBaselineAdded(Boolean baselineAdded) {
    this.baselineAdded = baselineAdded;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GridTransaction gridTransaction = (GridTransaction) o;
    return Objects.equals(this.txId, gridTransaction.txId) &&
        Objects.equals(this.txCreatedByEmail, gridTransaction.txCreatedByEmail) &&
        Objects.equals(this.txCreationTimeUTC, gridTransaction.txCreationTimeUTC) &&
        Objects.equals(this.comment, gridTransaction.comment) &&
        Objects.equals(this.rowAdded, gridTransaction.rowAdded) &&
        Objects.equals(this.rowDeleted, gridTransaction.rowDeleted) &&
        Objects.equals(this.columnAdded, gridTransaction.columnAdded) &&
        Objects.equals(this.cellUpdated, gridTransaction.cellUpdated) &&
        Objects.equals(this.formulaUpdated, gridTransaction.formulaUpdated) &&
        Objects.equals(this.baselineAdded, gridTransaction.baselineAdded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txId, txCreatedByEmail, txCreationTimeUTC, comment, rowAdded, rowDeleted, columnAdded, cellUpdated, formulaUpdated, baselineAdded);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GridTransaction {\n");
    
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    txCreatedByEmail: ").append(toIndentedString(txCreatedByEmail)).append("\n");
    sb.append("    txCreationTimeUTC: ").append(toIndentedString(txCreationTimeUTC)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    rowAdded: ").append(toIndentedString(rowAdded)).append("\n");
    sb.append("    rowDeleted: ").append(toIndentedString(rowDeleted)).append("\n");
    sb.append("    columnAdded: ").append(toIndentedString(columnAdded)).append("\n");
    sb.append("    cellUpdated: ").append(toIndentedString(cellUpdated)).append("\n");
    sb.append("    formulaUpdated: ").append(toIndentedString(formulaUpdated)).append("\n");
    sb.append("    baselineAdded: ").append(toIndentedString(baselineAdded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

