/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.Neighborhood;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
/**
 * Relation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class Relation   {
  @JsonProperty("relationName")
  private String relationName = null;

  @JsonProperty("relatedNhId")
  private List<Neighborhood> relatedNhId = null;

  public Relation relationName(String relationName) {
    this.relationName = relationName;
    return this;
  }

  /**
   * Get relationName
   * @return relationName
   **/
  @JsonProperty("relationName")
  @ApiModelProperty(value = "")
  public String getRelationName() {
    return relationName;
  }

  public void setRelationName(String relationName) {
    this.relationName = relationName;
  }

  public Relation relatedNhId(List<Neighborhood> relatedNhId) {
    this.relatedNhId = relatedNhId;
    return this;
  }

  public Relation addRelatedNhIdItem(Neighborhood relatedNhIdItem) {
    if (this.relatedNhId == null) {
      this.relatedNhId = new ArrayList<Neighborhood>();
    }
    this.relatedNhId.add(relatedNhIdItem);
    return this;
  }

  /**
   * Get relatedNhId
   * @return relatedNhId
   **/
  @JsonProperty("relatedNhId")
  @ApiModelProperty(value = "")
  public List<Neighborhood> getRelatedNhId() {
    return relatedNhId;
  }

  public void setRelatedNhId(List<Neighborhood> relatedNhId) {
    this.relatedNhId = relatedNhId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Relation relation = (Relation) o;
    return Objects.equals(this.relationName, relation.relationName) &&
        Objects.equals(this.relatedNhId, relation.relatedNhId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(relationName, relatedNhId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Relation {\n");
    
    sb.append("    relationName: ").append(toIndentedString(relationName)).append("\n");
    sb.append("    relatedNhId: ").append(toIndentedString(relatedNhId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

