/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
/**
 * Row
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-09-18T12:35:03.779Z")
public class Row   {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("seqNo")
  private Float seqNo = null;

  @JsonProperty("previousRowid")
  private Integer previousRowid = null;

  @JsonProperty("previousRowOffset")
  private Integer previousRowOffset = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("rowName")
  private String rowName = null;

  @JsonProperty("tid")
  private Integer tid = null;

  @JsonProperty("ownerId")
  private Integer ownerId = null;

  @JsonProperty("ownerName")
  private String ownerName = null;

  @JsonProperty("creationTid")
  private Integer creationTid = null;

  @JsonProperty("createrId")
  private Integer createrId = null;

  @JsonProperty("ownershipAssignedTid")
  private Integer ownershipAssignedTid = null;

  public Row id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Row seqNo(Float seqNo) {
    this.seqNo = seqNo;
    return this;
  }

  /**
   * Get seqNo
   * @return seqNo
   **/
  @JsonProperty("seqNo")
  @ApiModelProperty(value = "")
  public Float getSeqNo() {
    return seqNo;
  }

  public void setSeqNo(Float seqNo) {
    this.seqNo = seqNo;
  }

  public Row previousRowid(Integer previousRowid) {
    this.previousRowid = previousRowid;
    return this;
  }

  /**
   * Get previousRowid
   * @return previousRowid
   **/
  @JsonProperty("previousRowid")
  @ApiModelProperty(value = "")
  public Integer getPreviousRowid() {
    return previousRowid;
  }

  public void setPreviousRowid(Integer previousRowid) {
    this.previousRowid = previousRowid;
  }

  public Row previousRowOffset(Integer previousRowOffset) {
    this.previousRowOffset = previousRowOffset;
    return this;
  }

  /**
   * Get previousRowOffset
   * @return previousRowOffset
   **/
  @JsonProperty("previousRowOffset")
  @ApiModelProperty(value = "")
  public Integer getPreviousRowOffset() {
    return previousRowOffset;
  }

  public void setPreviousRowOffset(Integer previousRowOffset) {
    this.previousRowOffset = previousRowOffset;
  }

  public Row active(Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active
   **/
  @JsonProperty("active")
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Row rowName(String rowName) {
    this.rowName = rowName;
    return this;
  }

  /**
   * Get rowName
   * @return rowName
   **/
  @JsonProperty("rowName")
  @ApiModelProperty(value = "")
  public String getRowName() {
    return rowName;
  }

  public void setRowName(String rowName) {
    this.rowName = rowName;
  }

  public Row tid(Integer tid) {
    this.tid = tid;
    return this;
  }

  /**
   * Get tid
   * @return tid
   **/
  @JsonProperty("tid")
  @ApiModelProperty(value = "")
  public Integer getTid() {
    return tid;
  }

  public void setTid(Integer tid) {
    this.tid = tid;
  }

  public Row ownerId(Integer ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * Get ownerId
   * @return ownerId
   **/
  @JsonProperty("ownerId")
  @ApiModelProperty(value = "")
  public Integer getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(Integer ownerId) {
    this.ownerId = ownerId;
  }

  public Row ownerName(String ownerName) {
    this.ownerName = ownerName;
    return this;
  }

  /**
   * Get ownerName
   * @return ownerName
   **/
  @JsonProperty("ownerName")
  @ApiModelProperty(value = "")
  public String getOwnerName() {
    return ownerName;
  }

  public void setOwnerName(String ownerName) {
    this.ownerName = ownerName;
  }

  public Row creationTid(Integer creationTid) {
    this.creationTid = creationTid;
    return this;
  }

  /**
   * Get creationTid
   * @return creationTid
   **/
  @JsonProperty("creationTid")
  @ApiModelProperty(value = "")
  public Integer getCreationTid() {
    return creationTid;
  }

  public void setCreationTid(Integer creationTid) {
    this.creationTid = creationTid;
  }

  public Row createrId(Integer createrId) {
    this.createrId = createrId;
    return this;
  }

  /**
   * Get createrId
   * @return createrId
   **/
  @JsonProperty("createrId")
  @ApiModelProperty(value = "")
  public Integer getCreaterId() {
    return createrId;
  }

  public void setCreaterId(Integer createrId) {
    this.createrId = createrId;
  }

  public Row ownershipAssignedTid(Integer ownershipAssignedTid) {
    this.ownershipAssignedTid = ownershipAssignedTid;
    return this;
  }

  /**
   * Get ownershipAssignedTid
   * @return ownershipAssignedTid
   **/
  @JsonProperty("ownershipAssignedTid")
  @ApiModelProperty(value = "")
  public Integer getOwnershipAssignedTid() {
    return ownershipAssignedTid;
  }

  public void setOwnershipAssignedTid(Integer ownershipAssignedTid) {
    this.ownershipAssignedTid = ownershipAssignedTid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Row row = (Row) o;
    return Objects.equals(this.id, row.id) &&
        Objects.equals(this.seqNo, row.seqNo) &&
        Objects.equals(this.previousRowid, row.previousRowid) &&
        Objects.equals(this.previousRowOffset, row.previousRowOffset) &&
        Objects.equals(this.active, row.active) &&
        Objects.equals(this.rowName, row.rowName) &&
        Objects.equals(this.tid, row.tid) &&
        Objects.equals(this.ownerId, row.ownerId) &&
        Objects.equals(this.ownerName, row.ownerName) &&
        Objects.equals(this.creationTid, row.creationTid) &&
        Objects.equals(this.createrId, row.createrId) &&
        Objects.equals(this.ownershipAssignedTid, row.ownershipAssignedTid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, seqNo, previousRowid, previousRowOffset, active, rowName, tid, ownerId, ownerName, creationTid, createrId, ownershipAssignedTid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Row {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    seqNo: ").append(toIndentedString(seqNo)).append("\n");
    sb.append("    previousRowid: ").append(toIndentedString(previousRowid)).append("\n");
    sb.append("    previousRowOffset: ").append(toIndentedString(previousRowOffset)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    rowName: ").append(toIndentedString(rowName)).append("\n");
    sb.append("    tid: ").append(toIndentedString(tid)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("    creationTid: ").append(toIndentedString(creationTid)).append("\n");
    sb.append("    createrId: ").append(toIndentedString(createrId)).append("\n");
    sb.append("    ownershipAssignedTid: ").append(toIndentedString(ownershipAssignedTid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

