/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.GridInfo;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)

/**
 * Whiteboard
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class Whiteboard   {
  @JsonProperty("wbId")
  private Integer wbId = null;

  @JsonProperty("wbName")
  private String wbName = null;

  @JsonProperty("gridList")
  private List<GridInfo> gridList = null;

  public Whiteboard wbId(Integer wbId) {
    this.wbId = wbId;
    return this;
  }

  /**
   * Get wbId
   * @return wbId
   **/
  @JsonProperty("wbId")
  @ApiModelProperty(value = "")
  public Integer getWbId() {
    return wbId;
  }

  public void setWbId(Integer wbId) {
    this.wbId = wbId;
  }

  public Whiteboard wbName(String wbName) {
    this.wbName = wbName;
    return this;
  }

  /**
   * Get wbName
   * @return wbName
   **/
  @JsonProperty("wbName")
  @ApiModelProperty(value = "")
  public String getWbName() {
    return wbName;
  }

  public void setWbName(String wbName) {
    this.wbName = wbName;
  }

  public Whiteboard gridList(List<GridInfo> gridList) {
    this.gridList = gridList;
    return this;
  }

  public Whiteboard addGridListItem(GridInfo gridListItem) {
    if (this.gridList == null) {
      this.gridList = new ArrayList<GridInfo>();
    }
    this.gridList.add(gridListItem);
    return this;
  }

  /**
   * Get gridList
   * @return gridList
   **/
  @JsonProperty("gridList")
  @ApiModelProperty(value = "")
  public List<GridInfo> getGridList() {
    return gridList;
  }

  public void setGridList(List<GridInfo> gridList) {
    this.gridList = gridList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Whiteboard whiteboard = (Whiteboard) o;
    return Objects.equals(this.wbId, whiteboard.wbId) &&
        Objects.equals(this.wbName, whiteboard.wbName) &&
        Objects.equals(this.gridList, whiteboard.gridList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wbId, wbName, gridList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Whiteboard {\n");
    
    sb.append("    wbId: ").append(toIndentedString(wbId)).append("\n");
    sb.append("    wbName: ").append(toIndentedString(wbName)).append("\n");
    sb.append("    gridList: ").append(toIndentedString(gridList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

