/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import com.fasterxml.jackson.annotation.JsonCreator;


/**
 * Gets or Sets CellChangeFlag
 */


public enum CellChangeFlag {
	  
	  VALUE_CHANGED (1),
	  FORMULA_CHANGED (2),
	  NEW_ROW (4),
	  NEW_COLUMN (8),
	  ROW_DELETED (16),
	  COLUMN_DELETED (32);

	  private int value;

	  CellChangeFlag(int value) {
	    this.value = value;
	  }

	  public int getvalue() {
	    return this.value;
	  }

/*}


public enum CellChangeFlag {
  
  VALUE("Value"),
  
  FORMULA("Formula"),
  
  CALCULATEDVALUE("CalculatedValue"),
  
  VALUEANDFORMULA("ValueAndFormula");

  private String value;

  CellChangeFlag(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }
*/
  @JsonCreator
  public static CellChangeFlag fromValue(int text) {
	    for (CellChangeFlag b : CellChangeFlag.values()) {
	      if (b.value  == text) {
	        return b;
	      }
	    }
	    return null;
	  }

/*  public static CellChangeFlag fromValue(String text) {
    for (CellChangeFlag b : CellChangeFlag.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }*/
}

