/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)

/**
 * ColumnChain
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class ColumnChain   {
  @JsonProperty("gridId")
  private Integer gridId = null;

  @JsonProperty("columnId")
  private Integer columnId = null;

  @JsonProperty("columnName")
  private String columnName = null;

  @JsonProperty("columnSequenceNumber")
  private Float columnSequenceNumber = null;

  @JsonProperty("previousColumnId")
  private Integer previousColumnId = null;

  @JsonProperty("previousColumnOffset")
  private Integer previousColumnOffset = null;

  @JsonProperty("columnType")
  private String columnType = null;

  @JsonProperty("columnWidth")
  private Integer columnWidth = null;

  @JsonProperty("columnSource")
  private String columnSource = null;

  @JsonProperty("isActive")
  private Boolean isActive = null;

  @JsonProperty("ownerUserId")
  private Integer ownerUserId = null;

  @JsonProperty("ownerEmail")
  private String ownerEmail = null;

  @JsonProperty("columnCreationTxId")
  private Integer columnCreationTxId = null;

  @JsonProperty("columnDeletionTxId")
  private Integer columnDeletionTxId = null;

  @JsonProperty("columnDeletionUserId")
  private Integer columnDeletionUserId = null;

  public ColumnChain gridId(Integer gridId) {
    this.gridId = gridId;
    return this;
  }

  /**
   * Get gridId
   * @return gridId
   **/
  @JsonProperty("gridId")
  @ApiModelProperty(value = "")
  public Integer getGridId() {
    return gridId;
  }

  public void setGridId(Integer gridId) {
    this.gridId = gridId;
  }

  public ColumnChain columnId(Integer columnId) {
    this.columnId = columnId;
    return this;
  }

  /**
   * Get columnId
   * @return columnId
   **/
  @JsonProperty("columnId")
  @ApiModelProperty(value = "")
  public Integer getColumnId() {
    return columnId;
  }

  public void setColumnId(Integer columnId) {
    this.columnId = columnId;
  }

  public ColumnChain columnName(String columnName) {
    this.columnName = columnName;
    return this;
  }

  /**
   * Get columnName
   * @return columnName
   **/
  @JsonProperty("columnName")
  @ApiModelProperty(value = "")
  public String getColumnName() {
    return columnName;
  }

  public void setColumnName(String columnName) {
    this.columnName = columnName;
  }

  public ColumnChain columnSequenceNumber(Float columnSequenceNumber) {
    this.columnSequenceNumber = columnSequenceNumber;
    return this;
  }

  /**
   * Get columnSequenceNumber
   * @return columnSequenceNumber
   **/
  @JsonProperty("columnSequenceNumber")
  @ApiModelProperty(value = "")
  public Float getColumnSequenceNumber() {
    return columnSequenceNumber;
  }

  public void setColumnSequenceNumber(Float columnSequenceNumber) {
    this.columnSequenceNumber = columnSequenceNumber;
  }

  public ColumnChain previousColumnId(Integer previousColumnId) {
    this.previousColumnId = previousColumnId;
    return this;
  }

  /**
   * Get previousColumnId
   * @return previousColumnId
   **/
  @JsonProperty("previousColumnId")
  @ApiModelProperty(value = "")
  public Integer getPreviousColumnId() {
    return previousColumnId;
  }

  public void setPreviousColumnId(Integer previousColumnId) {
    this.previousColumnId = previousColumnId;
  }

  public ColumnChain previousColumnOffset(Integer previousColumnOffset) {
    this.previousColumnOffset = previousColumnOffset;
    return this;
  }

  /**
   * Get previousColumnOffset
   * @return previousColumnOffset
   **/
  @JsonProperty("previousColumnOffset")
  @ApiModelProperty(value = "")
  public Integer getPreviousColumnOffset() {
    return previousColumnOffset;
  }

  public void setPreviousColumnOffset(Integer previousColumnOffset) {
    this.previousColumnOffset = previousColumnOffset;
  }

  public ColumnChain columnType(String columnType) {
    this.columnType = columnType;
    return this;
  }

  /**
   * Get columnType
   * @return columnType
   **/
  @JsonProperty("columnType")
  @ApiModelProperty(value = "")
  public String getColumnType() {
    return columnType;
  }

  public void setColumnType(String columnType) {
    this.columnType = columnType;
  }

  public ColumnChain columnWidth(Integer columnWidth) {
    this.columnWidth = columnWidth;
    return this;
  }

  /**
   * Get columnWidth
   * @return columnWidth
   **/
  @JsonProperty("columnWidth")
  @ApiModelProperty(value = "")
  public Integer getColumnWidth() {
    return columnWidth;
  }

  public void setColumnWidth(Integer columnWidth) {
    this.columnWidth = columnWidth;
  }

  public ColumnChain columnSource(String columnSource) {
    this.columnSource = columnSource;
    return this;
  }

  /**
   * Get columnSource
   * @return columnSource
   **/
  @JsonProperty("columnSource")
  @ApiModelProperty(value = "")
  public String getColumnSource() {
    return columnSource;
  }

  public void setColumnSource(String columnSource) {
    this.columnSource = columnSource;
  }

  public ColumnChain isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   **/
  @JsonProperty("isActive")
  @ApiModelProperty(value = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public ColumnChain ownerUserId(Integer ownerUserId) {
    this.ownerUserId = ownerUserId;
    return this;
  }

  /**
   * Get ownerUserId
   * @return ownerUserId
   **/
  @JsonProperty("ownerUserId")
  @ApiModelProperty(value = "")
  public Integer getOwnerUserId() {
    return ownerUserId;
  }

  public void setOwnerUserId(Integer ownerUserId) {
    this.ownerUserId = ownerUserId;
  }

  public ColumnChain ownerEmail(String ownerEmail) {
    this.ownerEmail = ownerEmail;
    return this;
  }

  /**
   * Get ownerEmail
   * @return ownerEmail
   **/
  @JsonProperty("ownerEmail")
  @ApiModelProperty(value = "")
  public String getOwnerEmail() {
    return ownerEmail;
  }

  public void setOwnerEmail(String ownerEmail) {
    this.ownerEmail = ownerEmail;
  }

  public ColumnChain columnCreationTxId(Integer columnCreationTxId) {
    this.columnCreationTxId = columnCreationTxId;
    return this;
  }

  /**
   * Get columnCreationTxId
   * @return columnCreationTxId
   **/
  @JsonProperty("columnCreationTxId")
  @ApiModelProperty(value = "")
  public Integer getColumnCreationTxId() {
    return columnCreationTxId;
  }

  public void setColumnCreationTxId(Integer columnCreationTxId) {
    this.columnCreationTxId = columnCreationTxId;
  }

  public ColumnChain columnDeletionTxId(Integer columnDeletionTxId) {
    this.columnDeletionTxId = columnDeletionTxId;
    return this;
  }

  /**
   * Get columnDeletionTxId
   * @return columnDeletionTxId
   **/
  @JsonProperty("columnDeletionTxId")
  @ApiModelProperty(value = "")
  public Integer getColumnDeletionTxId() {
    return columnDeletionTxId;
  }

  public void setColumnDeletionTxId(Integer columnDeletionTxId) {
    this.columnDeletionTxId = columnDeletionTxId;
  }

  public ColumnChain columnDeletionUserId(Integer columnDeletionUserId) {
    this.columnDeletionUserId = columnDeletionUserId;
    return this;
  }

  /**
   * Get columnDeletionUserId
   * @return columnDeletionUserId
   **/
  @JsonProperty("columnDeletionUserId")
  @ApiModelProperty(value = "")
  public Integer getColumnDeletionUserId() {
    return columnDeletionUserId;
  }

  public void setColumnDeletionUserId(Integer columnDeletionUserId) {
    this.columnDeletionUserId = columnDeletionUserId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ColumnChain columnChain = (ColumnChain) o;
    return Objects.equals(this.gridId, columnChain.gridId) &&
        Objects.equals(this.columnId, columnChain.columnId) &&
        Objects.equals(this.columnName, columnChain.columnName) &&
        Objects.equals(this.columnSequenceNumber, columnChain.columnSequenceNumber) &&
        Objects.equals(this.previousColumnId, columnChain.previousColumnId) &&
        Objects.equals(this.previousColumnOffset, columnChain.previousColumnOffset) &&
        Objects.equals(this.columnType, columnChain.columnType) &&
        Objects.equals(this.columnWidth, columnChain.columnWidth) &&
        Objects.equals(this.columnSource, columnChain.columnSource) &&
        Objects.equals(this.isActive, columnChain.isActive) &&
        Objects.equals(this.ownerUserId, columnChain.ownerUserId) &&
        Objects.equals(this.ownerEmail, columnChain.ownerEmail) &&
        Objects.equals(this.columnCreationTxId, columnChain.columnCreationTxId) &&
        Objects.equals(this.columnDeletionTxId, columnChain.columnDeletionTxId) &&
        Objects.equals(this.columnDeletionUserId, columnChain.columnDeletionUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gridId, columnId, columnName, columnSequenceNumber, previousColumnId, previousColumnOffset, columnType, columnWidth, columnSource, isActive, ownerUserId, ownerEmail, columnCreationTxId, columnDeletionTxId, columnDeletionUserId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ColumnChain {\n");
    
    sb.append("    gridId: ").append(toIndentedString(gridId)).append("\n");
    sb.append("    columnId: ").append(toIndentedString(columnId)).append("\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    columnSequenceNumber: ").append(toIndentedString(columnSequenceNumber)).append("\n");
    sb.append("    previousColumnId: ").append(toIndentedString(previousColumnId)).append("\n");
    sb.append("    previousColumnOffset: ").append(toIndentedString(previousColumnOffset)).append("\n");
    sb.append("    columnType: ").append(toIndentedString(columnType)).append("\n");
    sb.append("    columnWidth: ").append(toIndentedString(columnWidth)).append("\n");
    sb.append("    columnSource: ").append(toIndentedString(columnSource)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    ownerUserId: ").append(toIndentedString(ownerUserId)).append("\n");
    sb.append("    ownerEmail: ").append(toIndentedString(ownerEmail)).append("\n");
    sb.append("    columnCreationTxId: ").append(toIndentedString(columnCreationTxId)).append("\n");
    sb.append("    columnDeletionTxId: ").append(toIndentedString(columnDeletionTxId)).append("\n");
    sb.append("    columnDeletionUserId: ").append(toIndentedString(columnDeletionUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

