/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
/**
 * FormulaValue
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class FormulaValue   {
  @JsonProperty("formulaId")
  private Integer formulaId = null;

  @JsonProperty("formula")
  private String formula = null;

  @JsonProperty("formulaIndex")
  private String formulaIndex = null;

  @JsonProperty("txId")
  private Integer txId = null;

  public FormulaValue formulaId(Integer formulaId) {
    this.formulaId = formulaId;
    return this;
  }

  /**
   * Get formulaId
   * @return formulaId
   **/
  @JsonProperty("formulaId")
  @ApiModelProperty(value = "")
  public Integer getFormulaId() {
    return formulaId;
  }

  public void setFormulaId(Integer formulaId) {
    this.formulaId = formulaId;
  }

  public FormulaValue formula(String formula) {
    this.formula = formula;
    return this;
  }

  /**
   * Get formula
   * @return formula
   **/
  @JsonProperty("formula")
  @ApiModelProperty(value = "")
  public String getFormula() {
    return formula;
  }

  public void setFormula(String formula) {
    this.formula = formula;
  }

  public FormulaValue formulaIndex(String formulaIndex) {
    this.formulaIndex = formulaIndex;
    return this;
  }

  /**
   * Get formulaIndex
   * @return formulaIndex
   **/
  @JsonProperty("formulaIndex")
  @ApiModelProperty(value = "")
  public String getFormulaIndex() {
    return formulaIndex;
  }

  public void setFormulaIndex(String formulaIndex) {
    this.formulaIndex = formulaIndex;
  }

  public FormulaValue txId(Integer txId) {
    this.txId = txId;
    return this;
  }

  /**
   * Get txId
   * @return txId
   **/
  @JsonProperty("txId")
  @ApiModelProperty(value = "")
  public Integer getTxId() {
    return txId;
  }

  public void setTxId(Integer txId) {
    this.txId = txId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FormulaValue formulaValue = (FormulaValue) o;
    return Objects.equals(this.formulaId, formulaValue.formulaId) &&
        Objects.equals(this.formula, formulaValue.formula) &&
        Objects.equals(this.formulaIndex, formulaValue.formulaIndex) &&
        Objects.equals(this.txId, formulaValue.txId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(formulaId, formula, formulaIndex, txId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FormulaValue {\n");
    
    sb.append("    formulaId: ").append(toIndentedString(formulaId)).append("\n");
    sb.append("    formula: ").append(toIndentedString(formula)).append("\n");
    sb.append("    formulaIndex: ").append(toIndentedString(formulaIndex)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

