/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.ChangedCell;
import io.swagger.model.ColumnChain;
import io.swagger.model.RowChain;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

//@JsonInclude(JsonInclude.Include.NON_EMPTY)

/**
 * GridChangeBuffer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class GridChangeBuffer   {
  @JsonProperty("critical")
  private Integer critical = null;

  @JsonProperty("criticalLevel")
  private Integer criticalLevel = null;

  @JsonProperty("newRowArray")
  private List<RowChain> newRowArray = null;

  @JsonProperty("deletedRowArray")
  private List<Integer> deletedRowArray = null;

  @JsonProperty("newColumnArray")
  private List<ColumnChain> newColumnArray = null;

  @JsonProperty("deletedColumnArray")
  private List<Integer> deletedColumnArray = null;

  @JsonProperty("cellChanges")
  private List<ChangedCell> cellChanges = null;

  public GridChangeBuffer critical(Integer critical) {
    this.critical = critical;
    return this;
  }

  /**
   * Get critical
   * @return critical
   **/
  @JsonProperty("critical")
  @ApiModelProperty(value = "")
  public Integer getCritical() {
    return critical;
  }

  public void setCritical(Integer critical) {
    this.critical = critical;
  }

  public GridChangeBuffer criticalLevel(Integer criticalLevel) {
    this.criticalLevel = criticalLevel;
    return this;
  }

  /**
   * Get criticalLevel
   * @return criticalLevel
   **/
  @JsonProperty("criticalLevel")
  @ApiModelProperty(value = "")
  public Integer getCriticalLevel() {
    return criticalLevel;
  }

  public void setCriticalLevel(Integer criticalLevel) {
    this.criticalLevel = criticalLevel;
  }

  public GridChangeBuffer newRowArray(List<RowChain> newRowArray) {
    this.newRowArray = newRowArray;
    return this;
  }

  public GridChangeBuffer addNewRowArrayItem(RowChain newRowArrayItem) {
    if (this.newRowArray == null) {
      this.newRowArray = new ArrayList<RowChain>();
    }
    this.newRowArray.add(newRowArrayItem);
    return this;
  }

  /**
   * Get newRowArray
   * @return newRowArray
   **/
  @JsonProperty("newRowArray")
  @ApiModelProperty(value = "")
  public List<RowChain> getNewRowArray() {
    return newRowArray;
  }

  public void setNewRowArray(List<RowChain> newRowArray) {
    this.newRowArray = newRowArray;
  }

  public GridChangeBuffer deletedRowArray(List<Integer> deletedRowArray) {
    this.deletedRowArray = deletedRowArray;
    return this;
  }

  public GridChangeBuffer addDeletedRowArrayItem(Integer deletedRowArrayItem) {
    if (this.deletedRowArray == null) {
      this.deletedRowArray = new ArrayList<Integer>();
    }
    this.deletedRowArray.add(deletedRowArrayItem);
    return this;
  }

  /**
   * Get deletedRowArray
   * @return deletedRowArray
   **/
  @JsonProperty("deletedRowArray")
  @ApiModelProperty(value = "")
  public List<Integer> getDeletedRowArray() {
    return deletedRowArray;
  }

  public void setDeletedRowArray(List<Integer> deletedRowArray) {
    this.deletedRowArray = deletedRowArray;
  }

  public GridChangeBuffer newColumnArray(List<ColumnChain> newColumnArray) {
    this.newColumnArray = newColumnArray;
    return this;
  }

  public GridChangeBuffer addNewColumnArrayItem(ColumnChain newColumnArrayItem) {
    if (this.newColumnArray == null) {
      this.newColumnArray = new ArrayList<ColumnChain>();
    }
    this.newColumnArray.add(newColumnArrayItem);
    return this;
  }

  /**
   * Get newColumnArray
   * @return newColumnArray
   **/
  @JsonProperty("newColumnArray")
  @ApiModelProperty(value = "")
  public List<ColumnChain> getNewColumnArray() {
    return newColumnArray;
  }

  public void setNewColumnArray(List<ColumnChain> newColumnArray) {
    this.newColumnArray = newColumnArray;
  }

  public GridChangeBuffer deletedColumnArray(List<Integer> deletedColumnArray) {
    this.deletedColumnArray = deletedColumnArray;
    return this;
  }

  public GridChangeBuffer addDeletedColumnArrayItem(Integer deletedColumnArrayItem) {
    if (this.deletedColumnArray == null) {
      this.deletedColumnArray = new ArrayList<Integer>();
    }
    this.deletedColumnArray.add(deletedColumnArrayItem);
    return this;
  }

  /**
   * Get deletedColumnArray
   * @return deletedColumnArray
   **/
  @JsonProperty("deletedColumnArray")
  @ApiModelProperty(value = "")
  public List<Integer> getDeletedColumnArray() {
    return deletedColumnArray;
  }

  public void setDeletedColumnArray(List<Integer> deletedColumnArray) {
    this.deletedColumnArray = deletedColumnArray;
  }

  public GridChangeBuffer cellChanges(List<ChangedCell> cellChanges) {
    this.cellChanges = cellChanges;
    return this;
  }

  public GridChangeBuffer addCellChangesItem(ChangedCell cellChangesItem) {
    if (this.cellChanges == null) {
      this.cellChanges = new ArrayList<ChangedCell>();
    }
    this.cellChanges.add(cellChangesItem);
    return this;
  }

  /**
   * Get cellChanges
   * @return cellChanges
   **/
  @JsonProperty("cellChanges")
  @ApiModelProperty(value = "")
  public List<ChangedCell> getCellChanges() {
    return cellChanges;
  }

  public void setCellChanges(List<ChangedCell> cellChanges) {
    this.cellChanges = cellChanges;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GridChangeBuffer gridChangeBuffer = (GridChangeBuffer) o;
    return Objects.equals(this.critical, gridChangeBuffer.critical) &&
        Objects.equals(this.criticalLevel, gridChangeBuffer.criticalLevel) &&
        Objects.equals(this.newRowArray, gridChangeBuffer.newRowArray) &&
        Objects.equals(this.deletedRowArray, gridChangeBuffer.deletedRowArray) &&
        Objects.equals(this.newColumnArray, gridChangeBuffer.newColumnArray) &&
        Objects.equals(this.deletedColumnArray, gridChangeBuffer.deletedColumnArray) &&
        Objects.equals(this.cellChanges, gridChangeBuffer.cellChanges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(critical, criticalLevel, newRowArray, deletedRowArray, newColumnArray, deletedColumnArray, cellChanges);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GridChangeBuffer {\n");
    
    sb.append("    critical: ").append(toIndentedString(critical)).append("\n");
    sb.append("    criticalLevel: ").append(toIndentedString(criticalLevel)).append("\n");
    sb.append("    newRowArray: ").append(toIndentedString(newRowArray)).append("\n");
    sb.append("    deletedRowArray: ").append(toIndentedString(deletedRowArray)).append("\n");
    sb.append("    newColumnArray: ").append(toIndentedString(newColumnArray)).append("\n");
    sb.append("    deletedColumnArray: ").append(toIndentedString(deletedColumnArray)).append("\n");
    sb.append("    cellChanges: ").append(toIndentedString(cellChanges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

