/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
/**
 * Membership
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class Membership   {
  @JsonProperty("userId")
  private Integer userId = null;

  @JsonProperty("memberId")
  private Integer memberId = null;

  @JsonProperty("userEmail")
  private String userEmail = null;

  @JsonProperty("nhId")
  private Integer nhId = null;

  @JsonProperty("nhName")
  private String nhName = null;

  @JsonProperty("nhNamePath")
  private String nhNamePath = null;

  public Membership userId(Integer userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   **/
  @JsonProperty("userId")
  @ApiModelProperty(value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public Membership memberId(Integer memberId) {
    this.memberId = memberId;
    return this;
  }

  /**
   * Get memberId
   * @return memberId
   **/
  @JsonProperty("memberId")
  @ApiModelProperty(value = "")
  public Integer getMemberId() {
    return memberId;
  }

  public void setMemberId(Integer memberId) {
    this.memberId = memberId;
  }

  public Membership userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

  /**
   * Get userEmail
   * @return userEmail
   **/
  @JsonProperty("userEmail")
  @ApiModelProperty(value = "")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public Membership nhId(Integer nhId) {
    this.nhId = nhId;
    return this;
  }

  /**
   * Get nhId
   * @return nhId
   **/
  @JsonProperty("nhId")
  @ApiModelProperty(value = "")
  public Integer getNhId() {
    return nhId;
  }

  public void setNhId(Integer nhId) {
    this.nhId = nhId;
  }

  public Membership nhName(String nhName) {
    this.nhName = nhName;
    return this;
  }

  /**
   * Get nhName
   * @return nhName
   **/
  @JsonProperty("nhName")
  @ApiModelProperty(value = "")
  public String getNhName() {
    return nhName;
  }

  public void setNhName(String nhName) {
    this.nhName = nhName;
  }

  public Membership nhNamePath(String nhNamePath) {
    this.nhNamePath = nhNamePath;
    return this;
  }

  /**
   * Get nhNamePath
   * @return nhNamePath
   **/
  @JsonProperty("nhNamePath")
  @ApiModelProperty(value = "")
  public String getNhNamePath() {
    return nhNamePath;
  }

  public void setNhNamePath(String nhNamePath) {
    this.nhNamePath = nhNamePath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Membership membership = (Membership) o;
    return Objects.equals(this.userId, membership.userId) &&
        Objects.equals(this.memberId, membership.memberId) &&
        Objects.equals(this.userEmail, membership.userEmail) &&
        Objects.equals(this.nhId, membership.nhId) &&
        Objects.equals(this.nhName, membership.nhName) &&
        Objects.equals(this.nhNamePath, membership.nhNamePath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, memberId, userEmail, nhId, nhName, nhNamePath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Membership {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    memberId: ").append(toIndentedString(memberId)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    nhId: ").append(toIndentedString(nhId)).append("\n");
    sb.append("    nhName: ").append(toIndentedString(nhName)).append("\n");
    sb.append("    nhNamePath: ").append(toIndentedString(nhNamePath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

