/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
/**
 * Neighborhood
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class Neighborhood   {
  @JsonProperty("nhId")
  private Integer nhId = null;

  @JsonProperty("nhName")
  private String nhName = null;

  @JsonProperty("level")
  private Integer level = null;

  @JsonProperty("parentNhId")
  private Integer parentNhId = null;

  @JsonProperty("isSecure")
  private Boolean isSecure = false;

  public Neighborhood nhId(Integer nhId) {
    this.nhId = nhId;
    return this;
  }

  /**
   * Get nhId
   * @return nhId
   **/
  @JsonProperty("nhId")
  @ApiModelProperty(value = "")
  public Integer getNhId() {
    return nhId;
  }

  public void setNhId(Integer nhId) {
    this.nhId = nhId;
  }

  public Neighborhood nhName(String nhName) {
    this.nhName = nhName;
    return this;
  }

  /**
   * Get nhName
   * @return nhName
   **/
  @JsonProperty("nhName")
  @ApiModelProperty(value = "")
  public String getNhName() {
    return nhName;
  }

  public void setNhName(String nhName) {
    this.nhName = nhName;
  }

  public Neighborhood level(Integer level) {
    this.level = level;
    return this;
  }

  /**
   * Get level
   * @return level
   **/
  @JsonProperty("level")
  @ApiModelProperty(value = "")
  public Integer getLevel() {
    return level;
  }

  public void setLevel(Integer level) {
    this.level = level;
  }

  public Neighborhood parentNhId(Integer parentNhId) {
    this.parentNhId = parentNhId;
    return this;
  }

  /**
   * Get parentNhId
   * @return parentNhId
   **/
  @JsonProperty("parentNhId")
  @ApiModelProperty(value = "")
  public Integer getParentNhId() {
    return parentNhId;
  }

  public void setParentNhId(Integer parentNhId) {
    this.parentNhId = parentNhId;
  }

  public Neighborhood isSecure(Boolean isSecure) {
    this.isSecure = isSecure;
    return this;
  }

  /**
   * Get isSecure
   * @return isSecure
   **/
  @JsonProperty("isSecure")
  @ApiModelProperty(value = "")
  public Boolean isIsSecure() {
    return isSecure;
  }

  public void setIsSecure(Boolean isSecure) {
    this.isSecure = isSecure;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Neighborhood neighborhood = (Neighborhood) o;
    return Objects.equals(this.nhId, neighborhood.nhId) &&
        Objects.equals(this.nhName, neighborhood.nhName) &&
        Objects.equals(this.level, neighborhood.level) &&
        Objects.equals(this.parentNhId, neighborhood.parentNhId) &&
        Objects.equals(this.isSecure, neighborhood.isSecure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nhId, nhName, level, parentNhId, isSecure);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Neighborhood {\n");
    
    sb.append("    nhId: ").append(toIndentedString(nhId)).append("\n");
    sb.append("    nhName: ").append(toIndentedString(nhName)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    parentNhId: ").append(toIndentedString(parentNhId)).append("\n");
    sb.append("    isSecure: ").append(toIndentedString(isSecure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

