/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.model.RequestErrorInfo;
import io.swagger.model.ResponseErrorInfo;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)

/**
 * ResponseInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class ResponseInfo   {
  @JsonProperty("status")
  private String status = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("failureDetails")
  private List<ResponseErrorInfo> failureDetails = null;

  @JsonProperty("invalidRequestDetails")
  private List<RequestErrorInfo> invalidRequestDetails = null;

  public ResponseInfo status(String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   **/
  @JsonProperty("status")
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public ResponseInfo message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   **/
  @JsonProperty("message")
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ResponseInfo failureDetails(List<ResponseErrorInfo> failureDetails) {
    this.failureDetails = failureDetails;
    return this;
  }

  public ResponseInfo addFailureDetailsItem(ResponseErrorInfo failureDetailsItem) {
    if (this.failureDetails == null) {
      this.failureDetails = new ArrayList<ResponseErrorInfo>();
    }
    this.failureDetails.add(failureDetailsItem);
    return this;
  }

  /**
   * Get failureDetails
   * @return failureDetails
   **/
  @JsonProperty("failureDetails")
  @ApiModelProperty(value = "")
  public List<ResponseErrorInfo> getFailureDetails() {
    return failureDetails;
  }

  public void setFailureDetails(List<ResponseErrorInfo> failureDetails) {
    this.failureDetails = failureDetails;
  }

  public ResponseInfo invalidRequestDetails(List<RequestErrorInfo> invalidRequestDetails) {
    this.invalidRequestDetails = invalidRequestDetails;
    return this;
  }

  public ResponseInfo addInvalidRequestDetailsItem(RequestErrorInfo invalidRequestDetailsItem) {
    if (this.invalidRequestDetails == null) {
      this.invalidRequestDetails = new ArrayList<RequestErrorInfo>();
    }
    this.invalidRequestDetails.add(invalidRequestDetailsItem);
    return this;
  }

  /**
   * Get invalidRequestDetails
   * @return invalidRequestDetails
   **/
  @JsonProperty("invalidRequestDetails")
  @ApiModelProperty(value = "")
  public List<RequestErrorInfo> getInvalidRequestDetails() {
    return invalidRequestDetails;
  }

  public void setInvalidRequestDetails(List<RequestErrorInfo> invalidRequestDetails) {
    this.invalidRequestDetails = invalidRequestDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseInfo responseInfo = (ResponseInfo) o;
    return Objects.equals(this.status, responseInfo.status) &&
        Objects.equals(this.message, responseInfo.message) &&
        Objects.equals(this.failureDetails, responseInfo.failureDetails) &&
        Objects.equals(this.invalidRequestDetails, responseInfo.invalidRequestDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message, failureDetails, invalidRequestDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseInfo {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    failureDetails: ").append(toIndentedString(failureDetails)).append("\n");
    sb.append("    invalidRequestDetails: ").append(toIndentedString(invalidRequestDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

