/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)

/**
 * RowChain
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class RowChain   {
  @JsonProperty("gridId")
  private Integer gridId = null;

  @JsonProperty("rowId")
  private Integer rowId = null;

  @JsonProperty("rowSequenceNumber")
  private Float rowSequenceNumber = null;

  @JsonProperty("previousRowId")
  private Integer previousRowId = null;

  @JsonProperty("previousRowOffset")
  private Integer previousRowOffset = null;

  @JsonProperty("isActive")
  private Boolean isActive = null;

  @JsonProperty("rowName")
  private String rowName = null;

  @JsonProperty("ownerUserId")
  private Integer ownerUserId = null;

  @JsonProperty("ownerEmail")
  private String ownerEmail = null;

  @JsonProperty("ownershipAssignedTxId")
  private Integer ownershipAssignedTxId = null;

  @JsonProperty("rowCreationTxId")
  private Integer rowCreationTxId = null;

  @JsonProperty("rowCreatorUserId")
  private Integer rowCreatorUserId = null;

  @JsonProperty("rowDeletionTxId")
  private Integer rowDeletionTxId = null;

  @JsonProperty("rowDeletionUserId")
  private Integer rowDeletionUserId = null;

  public RowChain gridId(Integer gridId) {
    this.gridId = gridId;
    return this;
  }

  /**
   * Get gridId
   * @return gridId
   **/
  @JsonProperty("gridId")
  @ApiModelProperty(value = "")
  public Integer getGridId() {
    return gridId;
  }

  public void setGridId(Integer gridId) {
    this.gridId = gridId;
  }

  public RowChain rowId(Integer rowId) {
    this.rowId = rowId;
    return this;
  }

  /**
   * Get rowId
   * @return rowId
   **/
  @JsonProperty("rowId")
  @ApiModelProperty(value = "")
  public Integer getRowId() {
    return rowId;
  }

  public void setRowId(Integer rowId) {
    this.rowId = rowId;
  }

  public RowChain rowSequenceNumber(Float rowSequenceNumber) {
    this.rowSequenceNumber = rowSequenceNumber;
    return this;
  }

  /**
   * Get rowSequenceNumber
   * @return rowSequenceNumber
   **/
  @JsonProperty("rowSequenceNumber")
  @ApiModelProperty(value = "")
  public Float getRowSequenceNumber() {
    return rowSequenceNumber;
  }

  public void setRowSequenceNumber(Float rowSequenceNumber) {
    this.rowSequenceNumber = rowSequenceNumber;
  }

  public RowChain previousRowId(Integer previousRowId) {
    this.previousRowId = previousRowId;
    return this;
  }

  /**
   * Get previousRowId
   * @return previousRowId
   **/
  @JsonProperty("previousRowId")
  @ApiModelProperty(value = "")
  public Integer getPreviousRowId() {
    return previousRowId;
  }

  public void setPreviousRowId(Integer previousRowId) {
    this.previousRowId = previousRowId;
  }

  public RowChain previousRowOffset(Integer previousRowOffset) {
    this.previousRowOffset = previousRowOffset;
    return this;
  }

  /**
   * Get previousRowOffset
   * @return previousRowOffset
   **/
  @JsonProperty("previousRowOffset")
  @ApiModelProperty(value = "")
  public Integer getPreviousRowOffset() {
    return previousRowOffset;
  }

  public void setPreviousRowOffset(Integer previousRowOffset) {
    this.previousRowOffset = previousRowOffset;
  }

  public RowChain isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   **/
  @JsonProperty("isActive")
  @ApiModelProperty(value = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public RowChain rowName(String rowName) {
    this.rowName = rowName;
    return this;
  }

  /**
   * Get rowName
   * @return rowName
   **/
  @JsonProperty("rowName")
  @ApiModelProperty(value = "")
  public String getRowName() {
    return rowName;
  }

  public void setRowName(String rowName) {
    this.rowName = rowName;
  }

  public RowChain ownerUserId(Integer ownerUserId) {
    this.ownerUserId = ownerUserId;
    return this;
  }

  /**
   * Get ownerUserId
   * @return ownerUserId
   **/
  @JsonProperty("ownerUserId")
  @ApiModelProperty(value = "")
  public Integer getOwnerUserId() {
    return ownerUserId;
  }

  public void setOwnerUserId(Integer ownerUserId) {
    this.ownerUserId = ownerUserId;
  }

  public RowChain ownerEmail(String ownerEmail) {
    this.ownerEmail = ownerEmail;
    return this;
  }

  /**
   * Get ownerEmail
   * @return ownerEmail
   **/
  @JsonProperty("ownerEmail")
  @ApiModelProperty(value = "")
  public String getOwnerEmail() {
    return ownerEmail;
  }

  public void setOwnerEmail(String ownerEmail) {
    this.ownerEmail = ownerEmail;
  }

  public RowChain ownershipAssignedTxId(Integer ownershipAssignedTxId) {
    this.ownershipAssignedTxId = ownershipAssignedTxId;
    return this;
  }

  /**
   * Get ownershipAssignedTxId
   * @return ownershipAssignedTxId
   **/
  @JsonProperty("ownershipAssignedTxId")
  @ApiModelProperty(value = "")
  public Integer getOwnershipAssignedTxId() {
    return ownershipAssignedTxId;
  }

  public void setOwnershipAssignedTxId(Integer ownershipAssignedTxId) {
    this.ownershipAssignedTxId = ownershipAssignedTxId;
  }

  public RowChain rowCreationTxId(Integer rowCreationTxId) {
    this.rowCreationTxId = rowCreationTxId;
    return this;
  }

  /**
   * Get rowCreationTxId
   * @return rowCreationTxId
   **/
  @JsonProperty("rowCreationTxId")
  @ApiModelProperty(value = "")
  public Integer getRowCreationTxId() {
    return rowCreationTxId;
  }

  public void setRowCreationTxId(Integer rowCreationTxId) {
    this.rowCreationTxId = rowCreationTxId;
  }

  public RowChain rowCreatorUserId(Integer rowCreatorUserId) {
    this.rowCreatorUserId = rowCreatorUserId;
    return this;
  }

  /**
   * Get rowCreatorUserId
   * @return rowCreatorUserId
   **/
  @JsonProperty("rowCreatorUserId")
  @ApiModelProperty(value = "")
  public Integer getRowCreatorUserId() {
    return rowCreatorUserId;
  }

  public void setRowCreatorUserId(Integer rowCreatorUserId) {
    this.rowCreatorUserId = rowCreatorUserId;
  }

  public RowChain rowDeletionTxId(Integer rowDeletionTxId) {
    this.rowDeletionTxId = rowDeletionTxId;
    return this;
  }

  /**
   * Get rowDeletionTxId
   * @return rowDeletionTxId
   **/
  @JsonProperty("rowDeletionTxId")
  @ApiModelProperty(value = "")
  public Integer getRowDeletionTxId() {
    return rowDeletionTxId;
  }

  public void setRowDeletionTxId(Integer rowDeletionTxId) {
    this.rowDeletionTxId = rowDeletionTxId;
  }

  public RowChain rowDeletionUserId(Integer rowDeletionUserId) {
    this.rowDeletionUserId = rowDeletionUserId;
    return this;
  }

  /**
   * Get rowDeletionUserId
   * @return rowDeletionUserId
   **/
  @JsonProperty("rowDeletionUserId")
  @ApiModelProperty(value = "")
  public Integer getRowDeletionUserId() {
    return rowDeletionUserId;
  }

  public void setRowDeletionUserId(Integer rowDeletionUserId) {
    this.rowDeletionUserId = rowDeletionUserId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RowChain rowChain = (RowChain) o;
    return Objects.equals(this.gridId, rowChain.gridId) &&
        Objects.equals(this.rowId, rowChain.rowId) &&
        Objects.equals(this.rowSequenceNumber, rowChain.rowSequenceNumber) &&
        Objects.equals(this.previousRowId, rowChain.previousRowId) &&
        Objects.equals(this.previousRowOffset, rowChain.previousRowOffset) &&
        Objects.equals(this.isActive, rowChain.isActive) &&
        Objects.equals(this.rowName, rowChain.rowName) &&
        Objects.equals(this.ownerUserId, rowChain.ownerUserId) &&
        Objects.equals(this.ownerEmail, rowChain.ownerEmail) &&
        Objects.equals(this.ownershipAssignedTxId, rowChain.ownershipAssignedTxId) &&
        Objects.equals(this.rowCreationTxId, rowChain.rowCreationTxId) &&
        Objects.equals(this.rowCreatorUserId, rowChain.rowCreatorUserId) &&
        Objects.equals(this.rowDeletionTxId, rowChain.rowDeletionTxId) &&
        Objects.equals(this.rowDeletionUserId, rowChain.rowDeletionUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gridId, rowId, rowSequenceNumber, previousRowId, previousRowOffset, isActive, rowName, ownerUserId, ownerEmail, ownershipAssignedTxId, rowCreationTxId, rowCreatorUserId, rowDeletionTxId, rowDeletionUserId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RowChain {\n");
    
    sb.append("    gridId: ").append(toIndentedString(gridId)).append("\n");
    sb.append("    rowId: ").append(toIndentedString(rowId)).append("\n");
    sb.append("    rowSequenceNumber: ").append(toIndentedString(rowSequenceNumber)).append("\n");
    sb.append("    previousRowId: ").append(toIndentedString(previousRowId)).append("\n");
    sb.append("    previousRowOffset: ").append(toIndentedString(previousRowOffset)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    rowName: ").append(toIndentedString(rowName)).append("\n");
    sb.append("    ownerUserId: ").append(toIndentedString(ownerUserId)).append("\n");
    sb.append("    ownerEmail: ").append(toIndentedString(ownerEmail)).append("\n");
    sb.append("    ownershipAssignedTxId: ").append(toIndentedString(ownershipAssignedTxId)).append("\n");
    sb.append("    rowCreationTxId: ").append(toIndentedString(rowCreationTxId)).append("\n");
    sb.append("    rowCreatorUserId: ").append(toIndentedString(rowCreatorUserId)).append("\n");
    sb.append("    rowDeletionTxId: ").append(toIndentedString(rowDeletionTxId)).append("\n");
    sb.append("    rowDeletionUserId: ").append(toIndentedString(rowDeletionUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

