/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_EMPTY)

/**
 * StatusChange
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-10-05T07:30:29.578Z")
public class StatusChange   {
  @JsonProperty("rowId")
  private Integer rowId = null;

  @JsonProperty("columnId")
  private Integer columnId = null;

  @JsonProperty("isActive")
  private Boolean isActive = null;

  @JsonProperty("txId")
  private Integer txId = null;

  @JsonProperty("txTimeUTC")
  private Date txTimeUTC = null;

  @JsonProperty("comment")
  private String comment = null;

  @JsonProperty("txUserEmail")
  private String txUserEmail = null;

  @JsonProperty("columnSequenceNumber")
  private Float columnSequenceNumber = null;

  @JsonProperty("rowSequenceNumber")
  private Float rowSequenceNumber = null;

  public StatusChange rowId(Integer rowId) {
    this.rowId = rowId;
    return this;
  }

  /**
   * Get rowId
   * @return rowId
   **/
  @JsonProperty("rowId")
  @ApiModelProperty(value = "")
  public Integer getRowId() {
    return rowId;
  }

  public void setRowId(Integer rowId) {
    this.rowId = rowId;
  }

  public StatusChange columnId(Integer columnId) {
    this.columnId = columnId;
    return this;
  }

  /**
   * Get columnId
   * @return columnId
   **/
  @JsonProperty("columnId")
  @ApiModelProperty(value = "")
  public Integer getColumnId() {
    return columnId;
  }

  public void setColumnId(Integer columnId) {
    this.columnId = columnId;
  }

  public StatusChange isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Get isActive
   * @return isActive
   **/
  @JsonProperty("isActive")
  @ApiModelProperty(value = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public StatusChange txId(Integer txId) {
    this.txId = txId;
    return this;
  }

  /**
   * Get txId
   * @return txId
   **/
  @JsonProperty("txId")
  @ApiModelProperty(value = "")
  public Integer getTxId() {
    return txId;
  }

  public void setTxId(Integer txId) {
    this.txId = txId;
  }

  public StatusChange txTimeUTC(Date txTimeUTC) {
    this.txTimeUTC = txTimeUTC;
    return this;
  }

  /**
   * Get txTimeUTC
   * @return txTimeUTC
   **/
  @JsonProperty("txTimeUTC")
  @ApiModelProperty(value = "")
  public Date getTxTimeUTC() {
    return txTimeUTC;
  }

  public void setTxTimeUTC(Date txTimeUTC) {
    this.txTimeUTC = txTimeUTC;
  }

  public StatusChange comment(String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Get comment
   * @return comment
   **/
  @JsonProperty("comment")
  @ApiModelProperty(value = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public StatusChange txUserEmail(String txUserEmail) {
    this.txUserEmail = txUserEmail;
    return this;
  }

  /**
   * Get txUserEmail
   * @return txUserEmail
   **/
  @JsonProperty("txUserEmail")
  @ApiModelProperty(value = "")
  public String getTxUserEmail() {
    return txUserEmail;
  }

  public void setTxUserEmail(String txUserEmail) {
    this.txUserEmail = txUserEmail;
  }

  public StatusChange columnSequenceNumber(Float columnSequenceNumber) {
    this.columnSequenceNumber = columnSequenceNumber;
    return this;
  }

  /**
   * Get columnSequenceNumber
   * @return columnSequenceNumber
   **/
  @JsonProperty("columnSequenceNumber")
  @ApiModelProperty(value = "")
  public Float getColumnSequenceNumber() {
    return columnSequenceNumber;
  }

  public void setColumnSequenceNumber(Float columnSequenceNumber) {
    this.columnSequenceNumber = columnSequenceNumber;
  }

  public StatusChange rowSequenceNumber(Float rowSequenceNumber) {
    this.rowSequenceNumber = rowSequenceNumber;
    return this;
  }

  /**
   * Get rowSequenceNumber
   * @return rowSequenceNumber
   **/
  @JsonProperty("rowSequenceNumber")
  @ApiModelProperty(value = "")
  public Float getRowSequenceNumber() {
    return rowSequenceNumber;
  }

  public void setRowSequenceNumber(Float rowSequenceNumber) {
    this.rowSequenceNumber = rowSequenceNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusChange statusChange = (StatusChange) o;
    return Objects.equals(this.rowId, statusChange.rowId) &&
        Objects.equals(this.columnId, statusChange.columnId) &&
        Objects.equals(this.isActive, statusChange.isActive) &&
        Objects.equals(this.txId, statusChange.txId) &&
        Objects.equals(this.txTimeUTC, statusChange.txTimeUTC) &&
        Objects.equals(this.comment, statusChange.comment) &&
        Objects.equals(this.txUserEmail, statusChange.txUserEmail) &&
        Objects.equals(this.columnSequenceNumber, statusChange.columnSequenceNumber) &&
        Objects.equals(this.rowSequenceNumber, statusChange.rowSequenceNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rowId, columnId, isActive, txId, txTimeUTC, comment, txUserEmail, columnSequenceNumber, rowSequenceNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusChange {\n");
    
    sb.append("    rowId: ").append(toIndentedString(rowId)).append("\n");
    sb.append("    columnId: ").append(toIndentedString(columnId)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    txTimeUTC: ").append(toIndentedString(txTimeUTC)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    txUserEmail: ").append(toIndentedString(txUserEmail)).append("\n");
    sb.append("    columnSequenceNumber: ").append(toIndentedString(columnSequenceNumber)).append("\n");
    sb.append("    rowSequenceNumber: ").append(toIndentedString(rowSequenceNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

