/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * StringValuesStrValueFormula
 */

public class StringValuesStrValueFormula   {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("stringValueId")
  private Integer stringValueId = null;

  @JsonProperty("formulaId")
  private Integer formulaId = null;

  public StringValuesStrValueFormula id(Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   **/
  @JsonProperty("id")
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public StringValuesStrValueFormula stringValueId(Integer stringValueId) {
    this.stringValueId = stringValueId;
    return this;
  }

  /**
   * Get stringValueId
   * @return stringValueId
   **/
  @JsonProperty("stringValueId")
  @ApiModelProperty(value = "")
  public Integer getStringValueId() {
    return stringValueId;
  }

  public void setStringValueId(Integer stringValueId) {
    this.stringValueId = stringValueId;
  }

  public StringValuesStrValueFormula formulaId(Integer formulaId) {
    this.formulaId = formulaId;
    return this;
  }

  /**
   * Get formulaId
   * @return formulaId
   **/
  @JsonProperty("formulaId")
  @ApiModelProperty(value = "")
  public Integer getFormulaId() {
    return formulaId;
  }

  public void setFormulaId(Integer formulaId) {
    this.formulaId = formulaId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StringValuesStrValueFormula stringValuesStrValueFormula = (StringValuesStrValueFormula) o;
    return Objects.equals(this.id, stringValuesStrValueFormula.id) &&
        Objects.equals(this.stringValueId, stringValuesStrValueFormula.stringValueId) &&
        Objects.equals(this.formulaId, stringValuesStrValueFormula.formulaId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, stringValueId, formulaId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StringValuesStrValueFormula {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    stringValueId: ").append(toIndentedString(stringValueId)).append("\n");
    sb.append("    formulaId: ").append(toIndentedString(formulaId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

