/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * StringValues
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2018-09-18T12:35:03.779Z")
public class StringValues   {
  @JsonProperty("cellId")
  private Integer cellId = null;

  @JsonProperty("stringValueId")
  private Integer stringValueId = null;

  @JsonProperty("stringValue")
  private String stringValue = null;

  @JsonProperty("txId")
  private Integer txId = null;

  @JsonProperty("formulaId")
  private Integer formulaId = null;

  public StringValues cellId(Integer cellId) {
    this.cellId = cellId;
    return this;
  }

  /**
   * Get cellId
   * @return cellId
   **/
  @JsonProperty("cellId")
  @ApiModelProperty(value = "")
  public Integer getCellId() {
    return cellId;
  }

  public void setCellId(Integer cellId) {
    this.cellId = cellId;
  }

  public StringValues stringValueId(Integer stringValueId) {
    this.stringValueId = stringValueId;
    return this;
  }

  /**
   * Get stringValueId
   * @return stringValueId
   **/
  @JsonProperty("stringValueId")
  @ApiModelProperty(value = "")
  public Integer getStringValueId() {
    return stringValueId;
  }

  public void setStringValueId(Integer stringValueId) {
    this.stringValueId = stringValueId;
  }

  public StringValues stringValue(String stringValue) {
    this.stringValue = stringValue;
    return this;
  }

  /**
   * Get stringValue
   * @return stringValue
   **/
  @JsonProperty("stringValue")
  @ApiModelProperty(value = "")
  public String getStringValue() {
    return stringValue;
  }

  public void setStringValue(String stringValue) {
    this.stringValue = stringValue;
  }

  public StringValues txId(Integer txId) {
    this.txId = txId;
    return this;
  }

  /**
   * Get txId
   * @return txId
   **/
  @JsonProperty("txId")
  @ApiModelProperty(value = "")
  public Integer getTxId() {
    return txId;
  }

  public void setTxId(Integer txId) {
    this.txId = txId;
  }

  public StringValues formulaId(Integer formulaId) {
    this.formulaId = formulaId;
    return this;
  }

  /**
   * Get formulaId
   * @return formulaId
   **/
  @JsonProperty("formulaId")
  @ApiModelProperty(value = "")
  public Integer getFormulaId() {
    return formulaId;
  }

  public void setFormulaId(Integer formulaId) {
    this.formulaId = formulaId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StringValues stringValues = (StringValues) o;
    return Objects.equals(this.cellId, stringValues.cellId) &&
        Objects.equals(this.stringValueId, stringValues.stringValueId) &&
        Objects.equals(this.stringValue, stringValues.stringValue) &&
        Objects.equals(this.txId, stringValues.txId) &&
        Objects.equals(this.formulaId, stringValues.formulaId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cellId, stringValueId, stringValue, txId, formulaId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StringValues {\n");
    
    sb.append("    cellId: ").append(toIndentedString(cellId)).append("\n");
    sb.append("    stringValueId: ").append(toIndentedString(stringValueId)).append("\n");
    sb.append("    stringValue: ").append(toIndentedString(stringValue)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    formulaId: ").append(toIndentedString(formulaId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

