/*
 * Boardwalk Cuboid Services
 * Boardwalk Rest API
 *
 * OpenAPI spec version: 1.0.2
 * Contact: apisupport@boardwalltech.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * TransactionChain
 */

public class TransactionChain   {
  @JsonProperty("gridId")
  private Long gridId = null;

  @JsonProperty("txId")
  private Long txId = null;

  @JsonProperty("txDateTimeGMT")
  private Long txDateTimeGMT = null;

  @JsonProperty("txDateTimeUTC")
  private Date txDateTimeUTC = null;

  @JsonProperty("txCreatedByName")
  private String txCreatedByName = null;

  @JsonProperty("txComment")
  private String txComment = null;

  @JsonProperty("txAction")
  private String txAction = null;

  public TransactionChain gridId(Long gridId) {
    this.gridId = gridId;
    return this;
  }

  /**
   * Get gridId
   * @return gridId
   **/
  @JsonProperty("gridId")
  @ApiModelProperty(value = "")
  public Long getGridId() {
    return gridId;
  }

  public void setGridId(Long gridId) {
    this.gridId = gridId;
  }

  public TransactionChain txId(Long txId) {
    this.txId = txId;
    return this;
  }

  /**
   * Get txId
   * @return txId
   **/
  @JsonProperty("txId")
  @ApiModelProperty(value = "")
  public Long getTxId() {
    return txId;
  }

  public void setTxId(Long txId) {
    this.txId = txId;
  }

  public TransactionChain txDateTimeGMT(Long txDateTimeGMT) {
    this.txDateTimeGMT = txDateTimeGMT;
    return this;
  }

  /**
   * Get txDateTimeGMT
   * @return txDateTimeGMT
   **/
  @JsonProperty("txDateTimeGMT")
  @ApiModelProperty(value = "")
  public Long getTxDateTimeGMT() {
    return txDateTimeGMT;
  }

  public void setTxDateTimeGMT(Long txDateTimeGMT) {
    this.txDateTimeGMT = txDateTimeGMT;
  }

  public TransactionChain txDateTimeUTC(Date txDateTimeUTC) {
    this.txDateTimeUTC = txDateTimeUTC;
    return this;
  }

  /**
   * Get txDateTimeUTC
   * @return txDateTimeUTC
   **/
  @JsonProperty("txDateTimeUTC")
  @ApiModelProperty(value = "")
  public Date getTxDateTimeUTC() {
    return txDateTimeUTC;
  }

  public void setTxDateTimeUTC(Date txDateTimeUTC) {
    this.txDateTimeUTC = txDateTimeUTC;
  }

  public TransactionChain txCreatedByName(String txCreatedByName) {
    this.txCreatedByName = txCreatedByName;
    return this;
  }

  /**
   * Get txCreatedByName
   * @return txCreatedByName
   **/
  @JsonProperty("txCreatedByName")
  @ApiModelProperty(value = "")
  public String getTxCreatedByName() {
    return txCreatedByName;
  }

  public void setTxCreatedByName(String txCreatedByName) {
    this.txCreatedByName = txCreatedByName;
  }

  public TransactionChain txComment(String txComment) {
    this.txComment = txComment;
    return this;
  }

  /**
   * Get txComment
   * @return txComment
   **/
  @JsonProperty("txComment")
  @ApiModelProperty(value = "")
  public String getTxComment() {
    return txComment;
  }

  public void setTxComment(String txComment) {
    this.txComment = txComment;
  }

  public TransactionChain txAction(String txAction) {
    this.txAction = txAction;
    return this;
  }

  /**
   * Get txAction
   * @return txAction
   **/
  @JsonProperty("txAction")
  @ApiModelProperty(value = "")
  public String getTxAction() {
    return txAction;
  }

  public void setTxAction(String txAction) {
    this.txAction = txAction;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionChain transactionChain = (TransactionChain) o;
    return Objects.equals(this.gridId, transactionChain.gridId) &&
        Objects.equals(this.txId, transactionChain.txId) &&
        Objects.equals(this.txDateTimeGMT, transactionChain.txDateTimeGMT) &&
        Objects.equals(this.txDateTimeUTC, transactionChain.txDateTimeUTC) &&
        Objects.equals(this.txCreatedByName, transactionChain.txCreatedByName) &&
        Objects.equals(this.txComment, transactionChain.txComment) &&
        Objects.equals(this.txAction, transactionChain.txAction);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gridId, txId, txDateTimeGMT, txDateTimeUTC, txCreatedByName, txComment, txAction);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionChain {\n");
    
    sb.append("    gridId: ").append(toIndentedString(gridId)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("    txDateTimeGMT: ").append(toIndentedString(txDateTimeGMT)).append("\n");
    sb.append("    txDateTimeUTC: ").append(toIndentedString(txDateTimeUTC)).append("\n");
    sb.append("    txCreatedByName: ").append(toIndentedString(txCreatedByName)).append("\n");
    sb.append("    txComment: ").append(toIndentedString(txComment)).append("\n");
    sb.append("    txAction: ").append(toIndentedString(txAction)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

